repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
-   repo: https://github.com/hhatto/autopep8
    rev: v2.1.0
    hooks:
    -   id: autopep8
-   repo: https://github.com/python-poetry/poetry
    rev: '1.8.2'
    hooks:
    -   id: poetry-check
    -   id: poetry-lock
    -   id: poetry-export
    -   id: poetry-install
-   repo: local
    hooks:
      - id: check-version-message-commit-msg
        name: Check Version Message (Commit-Msg Hook)
        entry: poetry run python tools/scripts/version.py
        language: system
        stages: [commit-msg]
      - id: create-commit-tags
        name: Create Commit Tags
        entry: poetry run python tools/scripts/tag.py
        language: system
        stages: [post-commit]
        args: [
          "--commit-message-path",
          ".git/COMMIT_EDITMSG",
        ]
        always_run: true
