[tool.poetry]
name = "tools"
version = "0.1.0"
description = "A semi-structured collection of general tools and functions that I have implemented for my research projects."
authors = ["Jan Philipp Schneider <jp-schneider@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.26.4"
pandas = "^2.2.1"
torch = {version = "^2.2.1", optional = true}
torchvision = {version = "^0.17.1", optional = true}
torchaudio = {version = "^2.2.1", optional = true}
dill = {version = "^0.3.8", optional = true}
simple-parsing = "^0.1.5"
typing-inspect = "^0.9.0"
scikit-learn = {version = "^1.4.1.post1", optional = true}
jsonpickle = {version = "^3.0.3", optional = true}
tqdm = "^4.66.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
